import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import {
  Stack,
  Grid,
  Image,
  Title,
  Text,
  createStyles,
  Box,
  BackgroundImage,
} from '@mantine/core'
import { COLOR_MUD } from '../utils/constants'

const useStyles = createStyles(() => ({
  section: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
}))

const Home: NextPage = () => {
  const { classes } = useStyles()
  return (
    <div>
      <Head>
        <title>Olives</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Grid gutter="md" mt={32} p={16}>
          <Grid.Col xs={6}>
            <Image
              src="/olive-oil-bottle.jpg"
              alt="olive oil in a bottle"
              height={300}
            />
          </Grid.Col>
          <Grid.Col xs={6}>
            <Stack>
              <Box>
                <Image src="/yellow-brush.svg" width={140} />
                <Title color={COLOR_MUD}>WHO WE ARE</Title>
              </Box>
              <Text>
                Olives is proud to deliver high quality standards. In natural
                environment production, delivery, and flexibility. Organic bio
                oil in a special production from our farm.
              </Text>
              <Link href="#">
                <Text color={COLOR_MUD}>READ MORE</Text>
              </Link>
            </Stack>
          </Grid.Col>
          <Grid.Col xs={12} mt={32} className={classes.section}>
            <Box>
              <Image src="/yellow-brush.svg" width={140} />
              <Title color={COLOR_MUD}>WHAT WE DO</Title>
            </Box>
            <Image src="/olive-tree.jpg" px={16} height={400} />
          </Grid.Col>
          <Grid.Col xs={12}>
            <BackgroundImage src="/quote-bg.png">
              <Text>
                "Health is wealth, it is always better when it is natural."
              </Text>
              <Text>@crestodina </Text>
            </BackgroundImage>
          </Grid.Col>
        </Grid>
      </main>
    </div>
  )
}

export default Home
